import express from "express";
import { createServer as createViteServer } from "vite";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function startServer() {
  const app = express();
  const PORT = 3000;

  // API Route for the setup script
  app.get("/setup.sh", (req, res) => {
    const script = `#!/bin/bash
# Termux Retro Setup - Automated XFCE + Chicago95
# Generated by AI Studio App

set -e

echo "[*] Starting automated Termux Linux setup..."

# 1. Update Termux
pkg update -y && pkg upgrade -y

# 2. Install required packages
pkg install -y git curl wget pulseaudio x11-repo

# 3. Download the original setup script
echo "[*] Fetching base setup script..."
curl -LO https://raw.githubusercontent.com/orailnoor/termux-linux-setup/main/termux-linux-setup.sh
chmod +x termux-linux-setup.sh

# 4. Run the setup script with automated answers
# Assuming XFCE is option '1' (common in these scripts)
# We use 'yes 1' or a heredoc to provide answers
echo "[*] Running base setup (this may take a while)..."
# We'll try to use a heredoc for standard choices: 
# 1 (XFCE), then maybe some defaults
./termux-linux-setup.sh <<EOF
1
y
y
EOF

# 5. Install Chicago95 Theme
echo "[*] Installing Chicago95 Theme..."
git clone https://github.com/GrassfedBadge/Chicago95.git ~/Chicago95 || true

# Apply Theme Files
mkdir -p ~/.local/share/themes ~/.local/share/icons ~/.local/share/fonts
cp -r ~/Chicago95/Theme/Chicago95 ~/.local/share/themes/
cp -r ~/Chicago95/Icons/* ~/.local/share/icons/
cp -r ~/Chicago95/Fonts/* ~/.local/share/fonts/
fc-cache -fv

# 6. Apply XFCE Settings (Non-interactive)
echo "[*] Configuring XFCE to use Chicago95..."
if command -v xfconf-query >/dev/null; then
    xfconf-query -c xsettings -p /Net/ThemeName -s "Chicago95" || true
    xfconf-query -c xsettings -p /Net/IconThemeName -s "Chicago95" || true
    xfconf-query -c xfwm4 -p /general/theme -s "Chicago95" || true
    # Set font if available
    xfconf-query -c xsettings -p /Gtk/FontName -s "Sans 10" || true
fi

echo "[!] Setup complete! You can now start your desktop using 'start-desktop' (or whatever command the base script provided)."
echo "[!] Enjoy your Retro Linux environment!"
`;
    res.setHeader("Content-Type", "text/x-shellscript");
    res.send(script);
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
