#!/bin/bash
# Termux Retro Setup - Automated XFCE + Chicago95
# Generated by AI Studio App

set -e

echo "[*] Starting automated Termux Linux setup..."

# 1. Update Termux
pkg update -y && pkg upgrade -y

# 2. Install required packages
pkg install -y git curl wget pulseaudio x11-repo

# 3. Download the original setup script
echo "[*] Fetching base setup script..."
curl -LO https://raw.githubusercontent.com/orailnoor/termux-linux-setup/main/termux-linux-setup.sh
chmod +x termux-linux-setup.sh

# 4. Run the setup script with automated answers
# Assuming XFCE is option '1' (common in these scripts)
echo "[*] Running base setup (this may take a while)..."
./termux-linux-setup.sh <<EOF
1
y
y
EOF

# 5. Install Chicago95 Theme
echo "[*] Installing Chicago95 Theme..."
git clone https://github.com/GrassfedBadge/Chicago95.git ~/Chicago95 || true

# Apply Theme Files
mkdir -p ~/.local/share/themes ~/.local/share/icons ~/.local/share/fonts
cp -r ~/Chicago95/Theme/Chicago95 ~/.local/share/themes/
cp -r ~/Chicago95/Icons/* ~/.local/share/icons/
cp -r ~/Chicago95/Fonts/* ~/.local/share/fonts/
fc-cache -fv

# 6. Apply XFCE Settings (Non-interactive)
echo "[*] Configuring XFCE to use Chicago95..."
if command -v xfconf-query >/dev/null; then
    xfconf-query -c xsettings -p /Net/ThemeName -s "Chicago95" || true
    xfconf-query -c xsettings -p /Net/IconThemeName -s "Chicago95" || true
    xfconf-query -c xfwm4 -p /general/theme -s "Chicago95" || true
    # Set font if available
    xfconf-query -c xsettings -p /Gtk/FontName -s "Sans 10" || true
fi

echo "[!] Setup complete! You can now start your desktop using 'start-desktop'."
echo "[!] Enjoy your Retro Linux environment!"
